mode: train # train => train and test | inference => just test
resume: false # resume train from checkpoint

# hyperparameter
batch_size: 64
epochs: 300
learning_rate: 0.0005
lr_decay: 0.1
lr_decay_epochs: 100
weight_decay: 0.0002

# Dataset
dataset: camvid
dataset_dir: data/CamVid
width: 480
height: 360
weighting: enet
ignore_unlabeled: True

# Settings
worker: 4
print_step: false
imshow_batch: false
device: cuda

# save settings
name: ENet
save_dir: save
