mode: train # train / test / distill
model: deeplabv3 # enet / deeplabv3
resume: false # resume train from checkpoint
seed: 1

# deeplabv3 settings
pretrained: true # pretrained for backbone i.e. ResNet50
freeze: true # freeze the backbone

# hyperparameter
batch_size: 10
epochs: 300
learning_rate: 0.0005
lr_decay: 0.1
lr_decay_epochs: 100
weight_decay: 0.0002

# Dataset
dataset: camvid
dataset_dir: data/CamVid
width: 480
height: 360
weighing: enet
ignore_unlabeled: True

# Settings
workers: 4
print_step: false
imshow_batch: false
device: cuda

# save settings
name: ENet
save_dir: save

# teacher path
teacher_path: deeplabv3_imagenet

# layers to hook
teacher_layers:
  - backbone.layer2
  - backbone.layer3
  - backbone.layer4
  - classifier.1

student_layers:
  - regular2_4
  - dilated
  - regular4_1
  - regular5_1

# fine-tuning post-distillation
additional_epochs: 3
model_path: path