mode: train # train / test / distill
model: deeplabv3 # enet / deeplabv3
resume: false # resume train from checkpoint
seed: 1

# deeplabv3 settings
pretrained: true # pretrained for backbone i.e. ResNet50
freeze: true # freeze the backbone

# hyperparameter
batch_size: 10
epochs: 300
learning_rate: 0.0005
lr_decay: 0.1
lr_decay_epochs: 100
weight_decay: 0.0002

# Dataset
dataset: camvid
dataset_dir: data/CamVid
width: 480
height: 360
weighing: enet
ignore_unlabeled: True

# Settings
workers: 4
print_step: false
imshow_batch: false
device: cuda

# save settings
name: ENet
save_dir: save

# layers to hook
teacher_layers:
  - model.backbone.layer2
  - model.backbone.layer3
  - model.backbone.layer4
  - model.classifier.1

student_layers:
  - model.regular2_4
  - model.dilated
  - model.regular4_1
  - model.regular5_1